### ISSUE TITLE
You dont check for users using the universal cfg path for all steam clients

### ISSUE THREAD

**Issue by wazerstar** [komeg1/cs2res_fix#2] opened 2023-10-14 11:43 UTC
Example if you use this method you don't have to edit multiple files and folders, you will have the very same cs2_video.txt and autoexec/config for all your steam users, this was introduced many years ago and people have seem to forget this, and its kinda silly to use the "default" method.

info can be found here from changelog in 2015

```
[MISC]
– Users’ options are now stored independently in a Steam account-local data folder and can be different across Steam accounts on the same machine.
– Administrators setting up tournament Active Directory logons with Roaming Profiles can create a directory inside the user’s roaming profile storage and expose that location to the game by setting an environment variable USRLOCALCSGO=%USERPROFILE%\AppData\Roaming\csgo
```
https://blog.counter-strike.net/index.php/2015/12/13325/

So by this example below it will save your cs2_video.txt , autoexec, config etc in this folder

...\Steam\steamapps\common\Counter-Strike Global Offensive\game\csgo\cfg\

This is the regedit file I used to make it work like this and is used by many others.

Code below

```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Environment]
"USRLOCALCSGO"="C:\\Program Files (x86)\\Steam\\steamapps\\common\\Counter-Strike Global Offensive\\game\\csgo"
```

Zip file with .reg file created to double click and reboot machine after to take effect.
[cs2-universal-cfg-video-path.zip](https://github.com/komeg1/cs2res_fix/files/12904980/cs2-universal-cfg-video-path.zip)

This is obvious for windows only.

One last note, yes you still see CSGO paths and the name Counter-Strike Global Offensive because valve has not fixed that and its kinda  big oversight from them, they could easli make a script to detect files and move/rename folders etc to cs2.

**Comment by komeg1** [comment] 2023-12-04 22:40
Hey @wazerstar!

Sorry for the extended wait.
I've addressed the concern about environment variable by adding a new configuration option,`enableUniversalCfgPath` to the `cs2resfix.dll.config` file.  It basically replace all the paths with `{USERLOCALCSGO)/cfg` path and let you change the config in the path.

The changes are available on the [2-universal-cfg-cs2resfix branch](https://github.com/komeg1/cs2res_fix/tree/2-universal-cfg-cs2resfix).

Hope you can check if it works as intended. Until then I won't merge the branch with the master.

thank you for your valuable feedback.

**Comment by wazerstar** [comment] 2023-12-04 22:43
> Hey @wazerstar!
> 
> Sorry for the extended wait. I've addressed the concern about environment variable by adding a new configuration option,`enableUniversalCfgPath` to the `cs2resfix.dll.config` file. It basically replace all the paths with `{USERLOCALCSGO)/cfg` path and let you change the config in the path.
> 
> The changes are available on the [2-universal-cfg-cs2resfix branch](https://github.com/komeg1/cs2res_fix/tree/2-universal-cfg-cs2resfix).
> 
> Hope you can check if it works as intended. Until then I won't merge the branch with the master.
> 
> thank you for your valuable feedback.

Sure if there's compiled files.

**Comment by komeg1** [comment] 2023-12-04 22:45
just added - [v1.0.5](https://github.com/komeg1/cs2res_fix/releases/tag/v1.0.5)

**Comment by wazerstar** [comment] 2023-12-04 22:47
> just added - [v1.0.5](https://github.com/komeg1/cs2res_fix/releases/tag/v1.0.5)

Nothing happens when starting it, tried also to edit the file to true for uni path.

also only 88.5 KB compared to other releases, its very small :)

**Comment by komeg1** [comment] 2023-12-04 23:37
yeah my bad, check it [now](https://github.com/komeg1/cs2res_fix/releases/tag/v1.0.5)

**Comment by wazerstar** [comment] 2023-12-04 23:40
> yeah my bad, check it [now](https://github.com/komeg1/cs2res_fix/releases/tag/v1.0.5)

It reads its enabled but does not read the actually values in the file.

https://i.imgur.com/D9M97I8.png

also pressing open video/autoexec button opens the correct place.

**Comment by komeg1** [comment] 2023-12-04 23:47
the app itself doesn't read the values and fill the form for you, the 1920x1080 75hz was a placeholder since the beginning. But i will add it later for sure. If the value changing works let me know and i'll close the issue :). Thanks for the feedback

**Comment by wazerstar** [comment] 2023-12-05 00:04
> the app itself doesn't read the values and fill the form for you, the 1920x1080 75hz was a placeholder since the beginning. But i will add it later for sure. If the value changing works let me know and i'll close the issue :). Thanks for the feedback

You have an error and not accounting for other stuff that might have been added later?


The one that shows 2 aspect ratio is the one your tool mods, the other one was the backup I made before patching your tool.

https://streamable.com/qsw8ud
(sorry for the kids on discord eating chips and trash talking each other) sadly went into the recordings :)


You should also not touch version value, I see it was reverted back to 12 instead of 13

Guess in general, only read the values we want to change find the lines and edit those and nothing else.

**Comment by komeg1** [comment] 2023-12-05 01:16
i believe i've fixed everything you'd mentioned. [zip](https://github.com/komeg1/cs2res_fix/releases/tag/v1.0.5.1)

**Closed as completed** 2023-12-05 18:28 UTC
